apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: 512353534265.dkr.ecr.us-east-1.amazonaws.com/capstone
          ports:
            - containerPort: 3000
